# 公网注意端口和更改密码
version: "3.8"
services:
  pg:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always

  yajs:
    image: yajs
    ports:
      - "3000:3000"
    restart: always
    environment:
      pg: postgresql://postgres:123456@pg:5432/postgres
      redis: redis://redis:6379/0
      TZ: "Asia/Shanghai"
    volumes:
      - ./public:/app/public

  # web:
  #   image: nginx:1.25-alpine
  #   restart: always
  #   volumes:
  #   - ./conf.d:/etc/nginx/conf.d
  #   - ./www:/www
  #   - ./cert:/cert
  #   network_mode: host

volumes:
  pg:
    driver: local
